name: hydrated_bloc
description: An extension to the bloc state management library which automatically persists and restores bloc states.
version: 3.1.0
homepage: https://github.com/felangel/hydrated_bloc

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^3.0.0
  path: ^1.6.4
  path_provider: ^1.1.0
  synchronized: ^2.2.0
  encrypt: ^4.0.0
  crypto: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  effective_dart: ^1.1.1
  uuid: ^2.0.4
